on: push

name: hithub to jira

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: 'https://mdial89f.atlassian.net/jira'
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@v3
      with:
        issue: KS-2
        comment: ${{ github.event.pusher.name }} pushed to repository ${{ github.event.repository.Document }}
        
